#!/usr/bin/env bash

echo "setup..."

MODE='-v'
# simulation
#MODE="$MODE -n"

stow $MODE --dotfiles gitconfig-sergio

stow $MODE --dotfiles gitconfig-sergio-bare

stow $MODE --dotfiles gitconfig-sergio-gmail

stow $MODE --dotfiles gitconfig-workspace

stow $MODE --dotfiles gitconfig-from-pve
