#!/bin/bash

# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color|*-256color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
#force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	# We have color support; assume it's compliant with Ecma-48
	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
	# a case would tend to support setf rather than setaf.)
	color_prompt=yes
    else
	color_prompt=
    fi
fi

if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
unset color_prompt force_color_prompt

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# colored GCC warnings and errors
#export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi


# append at the end of your .bashrc file
# ssh agent
# eval `ssh-agent`
# https://serverfault.com/q/404447
# ssh -A -o UserKnownHostsFile=/dev/null ecsdotvm

# do not run a local agent!
# eval "$(ssh-agent -s)"

# disable temporarily to test git clone w/ agent key
# eval $(keychain --eval --agents ssh id_ed25519)

# eval $(keychain --inherit any --eval --agents ssh id_ed25519)

ssh-add ~/.ssh/id_ed25519

eval $(keychain --inherit any --eval --agents ssh id_ed25519)

keychain -l --query


# ssh-add -l

# export PATH="$HOME/bin:$PATH"
export PATH="$HOME/bin:$PATH"
export PATH="$HOME/workspace/SWIP-PMEP-2022-31/I2R-SWIP/code/docker-ubuntu:$PATH"


#
# https://blog.packagecloud.io/set-environment-variable-save-thousands-of-system-calls/
#
export TZ=:/etc/localtime

##
## PROMPT HACKING
##

# 

# NEW https://jakemccrary.com/blog/2020/04/21/using-bash-preexec-for-monitoring-the-runtime-of-your-last-command/
preexec() {
  if [ "UNSET" == "${timer}" ]; then
    timer=$SECONDS
  else
    timer=${timer:-$SECONDS}
  fi
}

precmd() {
  if [ "UNSET" == "${timer}" ]; then
     timer_show="0s"
  else
    the_seconds=$((SECONDS - timer))
    # use format-duration to make time more human readable
    timer_show="$(format-duration seconds $the_seconds)"
  fi
  timer="UNSET"
}

# export PS1='\n${debian_chroot:+($debian_chroot)}\[\033[1;32m\]\u@\h ${timer_show} \w\n\n\$\[\033[0;34m\] '
export PROMPT_COLOR_RED='\[\033[1;31m\]' # red
export PROMPT_COLOR_GREEN='\[\033[1;32m\]' # green
export PROMPT_COLOR_YELLOW='\[\033[1;33m\]' # yellow/orange
export PROMPT_COLOR_BLUE='\[\033[1;34m\]' # blue
export PROMPT_COLOR_PURPLE='\[\033[1;35m\]' # purple

export PROMPT_COLOR_WHITE='\[\033[1;37m\]' # white
export PROMPT_COLOR_DKGREY='\[\033[0;30m\]' # very dark grey
export PROMPT_COLOR_LTGREY='\e[38;2;150;150;150m' # light grey

# export PROMPT_COLOR_START='\[\033[0;31m\]' # red
export PROMPT_COLOR_DKORANGE='\[\033[0;33m\]' # dark orange
export PROMPT_COLOR_LTBLUE='\[\033[0;34m\]' # light blue
export PROMPT_COLOR_DKPURPLE='\[\033[0;35m\]' # dark purple
# export PROMPT_COLOR_START='\[\033[0;36m\]' # green
# export PROMPT_COLOR_START='\[\033[0;37m\]' # white

export PROMPT_COLOR_START=$PROMPT_COLOR_GREEN
export PROMPT_COLOR_END=$PROMPT_COLOR_WHITE

# PS1 and GIT PROMPT with 24h time and timer...
export PS1='\n${debian_chroot:+($debian_chroot)}'$PROMPT_COLOR_START'\u@\h'$PROMPT_COLOR_LTGREY' \D{%T} ${timer_show} '$PROMPT_COLOR_BLUE'\w\n\n'\
$PROMPT_COLOR_START'$'$PROMPT_COLOR_END' '

export GIT_PROMPT_START='\n'$PROMPT_COLOR_BLUE'\w\n'$PROMPT_COLOR_START'\u@\h'$PROMPT_COLOR_LTGREY' \D{%T} ${timer_show}'$PROMPT_COLOR_END
export GIT_PROMPT_END=" \n\n"$PROMPT_COLOR_START"$ "$PROMPT_COLOR_END

# export GIT_PROMPT_END=" \n\n"$PROMPT_COLOR_DKORANGE"$ "$PROMPT_COLOR_END

if [ -f "$HOME/bin/bash-git-prompt/gitprompt.sh" ]; then
    GIT_PROMPT_ONLY_IN_REPO=1
    # also set in /home/user/bin/gitprompt.sh

    # source "$HOME/.bash-git-prompt/gitprompt.sh"
    source "$HOME/bin/gitprompt.sh"
fi

# ruby for mdless
export PATH="$HOME/.local/share/gem/ruby/3.2.0/bin:$PATH"

# GNU source highlight
export LESSOPEN="| /usr/share/source-highlight/src-hilite-lesspipe.sh %s"
export LESS=' -R '

# GO
export PATH=$PATH:$HOME/go/bin:/usr/local/go/bin

# RUST cargo
export PATH=$PATH:$HOME/.cargo/bin

# open-in-editor https://github.com/dandavison/open-in-editor#
# export EDITOR='ne' && export OPEN_IN_EDITOR='ne'
# export EDITOR='vim' && export OPEN_IN_EDITOR='vim'
# export EDITOR='subl' && export OPEN_IN_EDITOR='subl'
# delta hyperlinks use lazyconfig
export EDITOR='Kone' && export OPEN_IN_EDITOR='Kone'

# SHOPT GLOB
shopt -s extglob 

# docker logs: unlimited!
export BUILDKIT_STEP_LOG_MAX_SIZE=-1
export BUILDKIT_STEP_LOG_MAX_SPEED=-1

# Set up fzf key bindings and fuzzy completion
eval "$(fzf --bash)"

# disable tailscale ssh
sudo tailscale set --ssh=false

# load secrets, if they exist
if [[ -f ~/.bashrc-secrets.sh ]]; then
    . ~/.bashrc-secrets.sh
fi


## ECSDOT
# use local ecsdot1 board with UART and JTAG /dev/ttyUSBx devices
unset ECSDOT1_SERVER

# use remote board server
# export ECSDOT1_SERVER=192.168.0.150


# PROMPT EXECUTION TIMER
# https://jakemccrary.com/blog/2020/04/21/using-bash-preexec-for-monitoring-the-runtime-of-your-last-command/

## LAST COMMAND !
# https://github.com/rcaloras/bash-preexec/
[[ -f ~/.bash-preexec.sh ]] && source ~/.bash-preexec.sh

